# Define the Arduino director (to find default libraries)

ARDUINO_DIR = /usr/share/arduino

# Where to find the arduino
# On the Raspberry an arduio will show up as ttyACM0 or ttyACM1 ...
# This will work if only 1 arduino is connected

ARDUINO_PORT = /dev/ttyUSB*

# Path for custom libraries

USER_LIB_PATH = /home/robin/sketchbook/libraries

# Define what board you are using

BOARD_TAG = nano328

# Reference the original Make file from the arduino-mk install

include /usr/share/arduino/Arduino.mk
